name: LateX Compiler

on: [push, pull_request]

jobs:
  kov0354:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compiling LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload LaTeX documents
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: kov0354.pdf
          path: main.pdf
          if-no-files-found: error
