@startuml playerTurn
|Systém|
start

:Vyhodnocení efektů;

|Uživatel|
:Zvolení dvou karet;
fork
  :Provedení prvků na kartách akcí;
fork again
  :Provedení akce poskoků;
end fork
:Propsání změn do systému;
:Zahození zvolených karet;

|Systém|
:Uvolnění efektů;
:Snížení počítadel poskoků;

stop
@enduml