@startuml restoreCards
|s| Systém
|u| Uživatel

|u|
start

|u|
:Výběr cíle obnovení;

if (Je výběr náhodný?) then (Ne)
    :Cíl si karty smí vybrat;
else (Ano)
    :Cíl si karty tahá náhodně;
endif

:Obnovení daného počtu karet;

|u|
stop
@enduml