@startuml summon
|s| Systém
|u| Uživatel

|u|
start

|u|
:Výběr cíle;
:Postavení poskoka na pozici;

:Zapsání poskoka do systému;

|s|
:Uložení nové entity;
:Zobrazení entity pod vyvolávačem;

|u|
:Položení karty na stůl;

|u|
stop
@enduml