openapi: 3.0.0
...
# 1) Define the key name and location
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-API-KEY  # name of the header, query parameter or cookie
  responses:
    UnauthorizedError:
      description: Unauthorized (invalid or missing API key)
      headers:
        WWW-Authenticate:
          schema:
            type: string
# 2) Apply the API key globally to all operations
security:
  - ApiKeyAuth: []     # use the same name as under securitySchemes


# 3) Apply the API key to a specific operation
paths:
  /something:
    get:
      # Operation-specific security:
      security:
        - ApiKeyAuth: []
      responses:
        '200':
          description: OK (successfully authenticated)
        '401':
          $ref: '#/components/responses/UnauthorizedError'