# Query
  query {
    user (id: 1) {
      name
      email
    }
  }


# Nested Query
  query {
    user(id: 1) {
      name
      email
      address {
        street
        city
        country {
          name
          capital
        }
      }
    }
  }
