name: Compile LaTeX - KOR0289

on:
  push:
    paths:
      - 'kor0289/**'
      - 'shared/**'
  pull_request:
    paths:
      - 'kor0289/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: DavidAnson/markdownlint-cli2-action@v13.0.0
        with:
          fix: true
          globs: 'kor0289/**/*.md'

  build-latex:
    runs-on: ubuntu-latest
    env: 
      ROAD: "\\newcommand{\\ROAD}{.}"
    steps:
      - uses: actions/checkout@v3

      - name: Compiling LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: kor0289/src
          args: -pdf -halt-on-error -synctex=1 -interaction=nonstopmode --shell-escape --enable-write18

      - name: Upload LaTeX documents
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: KOR0289-Thesis
          path: kor0289/src/main.pdf
          if-no-files-found: error

      - name: Upload LaTeX documents to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: kor0289/src/main.pdf
          target: /srv/tts-game/TTS-Docs/static/thesis/kor0289
          strip_components: 2

  restart:
    runs-on: ubuntu-latest
    needs: build-latex
    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            service tts-docs restart