name: Compile LaTeX - KOV0354

on:
  push:
    paths:
      - 'kov0354/**'
  pull_request:
    paths:
      - 'kov0354/**'
  workflow_dispatch:

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: DavidAnson/markdownlint-cli2-action@v13.0.0
        with:
          fix: true
          globs: 'kov0354/**/*.md'

  build-latex:
    runs-on: ubuntu-latest
    env: 
      ROAD: "\\newcommand{\\ROAD}{.}"
    steps:
      - uses: actions/checkout@v3

      # Fake display for plantuml
      - name: Set up Xvfb
        run: |
          sudo apt-get install -y xvfb
          sudo Xvfb :99 -ac -screen 0 1024x768x8 &
          export DISPLAY=:99
          export ROAD="\\newcommand{\\ROAD}{.}"

      - name: Compiling LaTeX documents
        env:
          ROAD: "\\newcommand{\\ROAD}{.}"
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: kov0354/src
          args: -pdf -halt-on-error -synctex=1 -interaction=nonstopmode --shell-escape --enable-write18
          extra_system_packages: 'inkscape openjdk17'
          docker_image: ghcr.io/xu-cheng/texlive-full:20240315

      - name: Upload LaTeX documents to artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: KOV0354-Thesis
          path: kov0354/src/main.pdf
          if-no-files-found: error

      - name: Upload LaTeX documents to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: kov0354/src/main.pdf
          target: /srv/tts-game/TTS-Docs/static/thesis/kov0354
          strip_components: 2

  restart:
    runs-on: ubuntu-latest
    needs: build-latex
    steps:
      - name: Execute SSH Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            service tts-docs restart