name: Compile and Upload LaTeX Documents

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Process LaTeX Document in latex_test
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: latex_test
        if: always() && success() && github.event_name == 'push'
        continue-on-error: true

      - name: Upload PDF from latex_test
        uses: actions/upload-artifact@v3
        if: success() && github.event_name == 'push'
        with:
          name: PDF-latex_test
          path: latex_test/main.pdf