name: Markdown Lint Check

on: [push, pull_request]

jobs:
  kor0289:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v3
        with:
          glob: 'kor0289/**/*.md'

  kov0354:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v3
        with:
          glob: 'kov0354/**/*.md'

  mik0486:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v3
        with:
          glob: 'mik0486/**/*.md'

  oso0008:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DavidAnson/markdownlint-cli2-action@v3
        with:
          glob: 'oso0008/**/*.md'
